# Generated by Django 2.1.2 on 2020-03-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_classification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product_classification',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
