# Generated by Django 2.1.2 on 2020-03-25 18:13

from django.db import migrations

category_options = (
    ('Chicken Breast Boneless Skinless'),
    ('Chicken Breast Bone-In Skinless '),
    ('Chicken Breast Bone-In Skin-On'),
    ('Chicken Thigh Boneless Skinless'),
    ('Chicken Thigh Bone-In Skin-On'),
    ('Chicken Leg'),
    ('Chicken Leg Quarters'),
    ('Chicken Wings'),
    ('Chicken Drumsticks'),
    ('Chicken Whole Birds (Fresh)'),
    ('Chicken Whole Birds (Frozen)'),
    ('Duck Breast Skin-On (Fresh)'),
    ('Duck Breast Skin-On (Frozen)'),
    ('Duck Whole Birds (Fresh)'),
    ('Duck Whole Birds (Frozen)'),
    ('Turkey Breasts Boneless Skinless'),
    ('Turkey Breasts Bone-In Skinless'),
    ('Turkey Breasts Bone-In Skin-On'),
    ('Turkey Drumsticks'),
    ('Turkey Legs'),
    ('Turkey Thighs'),
    ('Turkey Wings'),
    ('Turkey Whole Birds (Fresh)'),
    ('Turkey Whole Birds (Frozen)')
)

def populate_initial_data(apps, schema_editor):
    Category = apps.get_model('sprigs', 'Category')
    for category in category_options:
        Category.objects.bulk_create([Category(category=category)])

def reverse_function(apps, schema_editor):
    Category = apps.get_model('sprigs', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sprigs', '0003_auto_20200325_1509'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_function)
    ]